### ISSUE TITLE
Wiki lab0 does not mention the /api in end end of the apiurl

### ISSUE THREAD

**Issue by filipvh** [thinktecture/ngeurope-2018-pwa#1]
https://github.com/thinktecture/ngeurope-2018-pwa/wiki/Lab-0:-Setup-&-Verification-of-Final-Demo-Application#4-launch-client

Missing
see that the url end with /api
eg: https://xxxxxxxx.eu.ngrok.io/api

**Comment by christianliebel** [comment]
Fixed! Thanks a lot.
